name: Xbox360-LumenOS-Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Instalar Toolchain PowerPC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-powerpc-linux-gnu make libc6-dev-ppc-cross

      - name: Compilar App
        run: make

      - name: Upload do Binario (ELF)
        uses: actions/upload-artifact@v4
        with:
          name: Lumen-OS-Installer
          path: xenon.elf
