name: Xbox360-Build-System
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Instalar Compilador
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-powerpc-linux-gnu make

      - name: Compilar
        run: make
        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: App-Lumen-Xbox
          path: xenon.elf
