name: Xbox360-LumenOS-Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar GCC PowerPC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-powerpc-linux-gnu make

      - name: Compilar
        run: make

      - name: Salvar ELF
        uses: actions/upload-artifact@v4
        with:
          name: Lumen-OS-Binary
          path: xenon.elf
